### ISSUE TITLE
Implement LDAP account creation and deletion

### ISSUE THREAD

**Issue by vranki** [TampereHacklab/mulysa#10]
Listen to user activation signal, create or delete LDAP user if requested.

**Comment by tswfi** [comment]
also disable ldap user if requested

**Comment by olmari** [comment]
AFAIK indeed with OIDC/SSO-support implemented in Mulysa generally direct LDAP-integration is not really needed in Mulysa. if LDAP is _really_ wanted to be actual user database still, it can be set as SSO/Keycloak backend instead.

Though now as Mulysa can act as SSO-provider, the LDAP for user management is kinda surplus. though LDAP could still be usedwith computer/machine accounts where it was intended for).

**Comment by tswfi** [comment]
yup, closing this.
if / when this is needed we can always open new issues for this.
