### ISSUE TITLE
Mulysa FAQ

### ISSUE THREAD

**Issue by vranki** [TampereHacklab/mulysa#126]
Create a mulysa  FAQ somewhere (hacklab wiki / github?)

**Comment by tswfi** [comment]
github wiki for the parts that are global and unique parts in hacklab wiki?

**Comment by vranki** [comment]
In finnish:
https://wiki.tampere.hacklab.fi/palvelut#mulysa

**Comment by akusav** [comment]
In English:
https://tampere.hacklab.fi/pages/info-in-english/frequently-asked-questions/

**Comment by tswfi** [comment]
Thank you @akusav :heart:
