### ISSUE TITLE
Add a way for users to add nfc cards to their account

### ISSUE THREAD

**Issue by tswfi** [TampereHacklab/mulysa#150]
User has to first get the cardid from their card and then add it to the database as their card.

Perhaps build a small reader that can show the cardid and the user can then just manually write it down there..

Admins can check the request logs to the access endpoint to view the same information.

**Comment by vranki** [comment]
I'd do a UI in Mulysa that shows last unclaimed card with expiry time of 5 minutes. User could claim it as their own.

**Comment by vranki** [comment]
Done
