### ISSUE TITLE
Applying for membership with failing checks still generates custom user

### ISSUE THREAD

**Issue by olmari** [TampereHacklab/mulysa#162]
When someone fills out membership apply form and has some data that fails the checks, custom user is still created. This leads to `Custom user with this Email address already exists.` when data is corrected and tried to apply again.

I suspect custom users gets created before all the input data checks have passed.

**Comment by vranki** [comment]
Does this still happen? Could you give more details what kind of data that fails checks? Data validity is checked before anything is created in database.

**Comment by olmari** [comment]
I think this is fixed now, at least I couldn't reproduce it anymore with fresh master.
