### ISSUE TITLE
No "nick" in custom user

### ISSUE THREAD

**Issue by olmari** [TampereHacklab/mulysa#180]
I added phone/NFC query to tell also "nick" in 200 OK answer, but I got null for nick answer. I then realized that custom user does not have "nick" field. So we need to add it back, as not mandatory field.

**Comment by vranki** [comment]
Models.py:121 defines field nick for CustomUser. What do you mean?

**Comment by vranki** [comment]
Nick is there & can be self-edited in user settings.
