### ISSUE TITLE
PW reset email in finnish not 100% finnish

### ISSUE THREAD

**Issue by olmari** [TampereHacklab/mulysa#193]
```
Tämä viesti on lähetetty sinulle, koska olet pyytänyt Mulysa Dev Vaasa Hacklab -sivustolla salasanan palautusta.

Määrittele uusi salasanasi oheisella sivulla:

http://mulysa-dev.vaasa.hacklab.fi/www/reset/MTk/5ga-9401fec4b11e20366c38/

Your username, in case you’ve forgotten: sasd@saad.fi

Kiitos vierailustasi sivuillamme!

Mulysa Dev Vaasa Hacklab -sivuston ylläpitäjät
```

Figure how to change the last english text.

**Comment by vranki** [comment]
This seems to come from django's default template: https://github.com/django/django/blob/master/django/contrib/admin/templates/registration/password_reset_email.html

Why is that string not translated? Bug in django?

**Comment by tswfi** [comment]
@olmari can you retest, django has been updated in #206

**Comment by tswfi** [comment]
hmm, double checked django repo and it should be there

https://github.com/django/django/blob/master/django/contrib/admin/locale/fi/LC_MESSAGES/django.po#L658

**Comment by tswfi** [comment]
trying to add myself to django transifex project as there are few missing translations.

Created branch for this with a test case that fails: https://github.com/TampereHacklab/mulysa/pull/new/pwdreset_translation

run just this test
```
./manage.py test users.tests.TestNewApplicationHappyPathEmails        
```

**Comment by tswfi** [comment]
Got accepted to translation team.

**Comment by tswfi** [comment]
user akx (new fi maintainer) beat me to this :)

should be fixed in next django version.

![image](https://user-images.githubusercontent.com/1352132/101599771-0057d080-3a03-11eb-9b28-afa891c9d74e.png)

![image](https://user-images.githubusercontent.com/1352132/101599911-3c8b3100-3a03-11eb-844d-8690039dac62.png)

**Comment by tswfi** [comment]
@olmari want to retest now that django has been updated a few times between the last check :)

**Comment by tswfi** [comment]
Seems like this has been fixed in some update someday.

From my local dev environment email logging

```
[24/Sep/2022 20:39:11,016] REDACTED INFO Sending message Salasanan nollaus sivustolla Tampere Hacklab Mulysa  to recipients: ['tsw@REDACTED.fi'] with body: 
Tämä viesti on lähetetty sinulle, koska olet pyytänyt Tampere Hacklab Mulysa -sivustolla salasanan palautusta.

Määrittele uusi salasanasi oheisella sivulla:

http://localhost/www/reset/REDACTED/REDACTED/

Käyttäjätunnuksesi siltä varalta, että olet unohtanut sen: tsw@REDACTED.fi

Kiitos vierailustasi sivuillamme!

Tampere Hacklab Mulysa -sivuston ylläpitäjät


```
