### ISSUE TITLE
Update user should generate missing references for custom invoices

### ISSUE THREAD

**Issue by vranki** [TampereHacklab/mulysa#199]
Currently there seems to be no way to make custom invoices from admin as they don't get valid references.

**Comment by olmari** [comment]
Relating affecting issue is that admin user in UI-side can't create custom invoice for other users. `Create and view custom invoices` links to universal `createcustominvoice` without any user ID or so.

**Comment by vranki** [comment]
PR done but not tested - pending another PR.
