### ISSUE TITLE
Have all user data editable on one place instead many

### ISSUE THREAD

**Issue by olmari** [TampereHacklab/mulysa#201]
Currently there seems not to exist any method whatsoever to modify users nickname anywhere. by oneself nor by admin user, from UI nor Django-Admin side

**Comment by olmari** [comment]
Okay, found this one existing for exatly user oneself in `Change my settings. There is still no place for admin to change users nick in any view (UI nor admin).

Also why this separate section even exist? These datas shdould be exposed on the normal `Show my user information` where rest of user related data exists.

**Comment by vranki** [comment]
Changed tags as the issue seems to be about UI.

**Comment by tswfi** [comment]
@olmari Can you split this epic to smaller tasks now that #281 is merged?

**Comment by tswfi** [comment]
@olmari I'm guessing this can be closed?

**Comment by olmari** [comment]
I suppose this is done and dealt now, at least didn't find anything misplaced relating .
