### ISSUE TITLE
Mass email sending broken

### ISSUE THREAD

**Issue by tswfi** [TampereHacklab/mulysa#203]
![image](https://user-images.githubusercontent.com/1352132/83555433-f4042f80-a516-11ea-98fb-509d700ac742.png)

Seems to be this commit: https://github.com/TampereHacklab/mulysa/commit/dba909a132a378e032582841fa003d1a8fa4ea97#diff-3e8e52646c6f990687f12d5a76c4fc16R53 

which changed the template name but didn't rename the file...

**Comment by vranki** [comment]
PR in #208

**Comment by tswfi** [comment]
#208 fixed this
