### ISSUE TITLE
Generate reference number always when creating a MemberService

### ISSUE THREAD

**Issue by tswfi** [TampereHacklab/mulysa#237]
Check that the reference number is always created when adding services to users

**Comment by vranki** [comment]
Currently if you create one from admin manually, it has no ref number. Admin must press "Update user's data" to generate one.

**Comment by tswfi** [comment]
pretty sure these two fix this:

https://github.com/TampereHacklab/mulysa/pull/215
https://github.com/TampereHacklab/mulysa/pull/216
