### ISSUE TITLE
Ask for language during registration

### ISSUE THREAD

**Issue by vranki** [TampereHacklab/mulysa#238]
Finnish users tend to use default english and thus their language preference is wrong. Ask for language explicitly in registration form and set accordingly.

**Comment by tswfi** [comment]
Language is already asked while registering

![image](https://user-images.githubusercontent.com/1352132/101285380-86023300-37ed-11eb-96a5-df12dab22e0a.png)

And the language changes after filling that form and the "welcome" email is sent on that language.

and users language is also set after filling the registration form.

Closing this.
