### ISSUE TITLE
Implement more good looking web ui

### ISSUE THREAD

**Issue by vranki** [TampereHacklab/mulysa#24]
Current web ui is just a quick placeholder for demostrating features. 

Do a properly designed clean looking web ui based on the placeholder ui. Use proper REST API's where applicable. Split this issue to more tasks if needed.

**Comment by tswfi** [comment]
Started in #94

**Comment by tswfi** [comment]
At least something has been done with this now :)

**Comment by vranki** [comment]
I think it looks great now. Rest of UI finesse can be as separate enhancements.
