### ISSUE TITLE
Add automatic service suspension feature.

### ISSUE THREAD

**Issue by akusav** [TampereHacklab/mulysa#248]
If three payment reminder was delivered change service status "suspended".

**Comment by olmari** [comment]
There is already suspension where activation time can be defined per days overdue.

**Comment by tswfi** [comment]
@akusav is this not working or what is the issue?

**Comment by olmari** [comment]
Only reason I did not close this outright was the notion of three reminders, if that was the main driving force behind this issue. Indeed suspension already exists and is working and also one (and not three) remainder gets sent out predefined days before active time gets to overdue.

**Comment by tswfi** [comment]
I feel one notification should be enough, closing this.
