### ISSUE TITLE
Holvi-import doesn't import anything anymore

### ISSUE THREAD

**Issue by olmari** [TampereHacklab/mulysa#316]
Holvi-importer doesn't import anything, debug logs doesn't show anything actually failing, UI shows this:

![image](https://user-images.githubusercontent.com/5422161/111914994-ed7e7e80-8a7c-11eb-9458-b7f8c8621c2a.png)

**Comment by mikeful** [comment]
Excel export format seems to have changed in last few weeks(?).

Excel headers during development: `Date, Amount, Currency, Counterparty, Description, Reference, Message, Filing ID`

Excel headers exported today: `Payment date, Execution date, Amount, Currency, Counterparty, Description, Reference, Message, Filing ID
`
