### ISSUE TITLE
o/applications/ as normal "sub-page" in Mulysa

### ISSUE THREAD

**Issue by olmari** [TampereHacklab/mulysa#342]
Especially after https://github.com/TampereHacklab/mulysa/issues/341 make `o/applications/` normal "sub-page" on Mulysa, so it appears like any other page in mulysa instead as own top page without any menus and such.

**Comment by tswfi** [comment]
management of applications is not a "daily task" that needs its own page. the management can happen from django admin.

I think this can be closed and if we ever write our own mulysa admin we can raise this again.

**Comment by olmari** [comment]
Due https://github.com/TampereHacklab/mulysa/pull/343 this is no longer relevant.
