### ISSUE TITLE
Django-oauth-toolkit ver 2 is breaking change

### ISSUE THREAD

**Issue by olmari** [TampereHacklab/mulysa#365]
https://django-oauth-toolkit.readthedocs.io/en/latest/changelog.html#id5 tells that current "new" major version of Django-oauth-toolkit is breaking change, so we'd need to figure out our side for V2 and restrict version to 1.7.0 in mean time.

**Comment by tswfi** [comment]
Looks like all of those can be just changed with few settings or do not even affect us. Requires testing...

**Comment by olmari** [comment]
https://github.com/TampereHacklab/mulysa/commit/7f738fe8a513d635f96c47aebd540fdd510a9dde makes current instructions / current method of mulysa OIDC usage to keep working.
