### ISSUE TITLE
Browser password autofill messes up csrf token in sso login page

### ISSUE THREAD

**Issue by tswfi** [TampereHacklab/mulysa#452]
Steps to reproduce (chrome mobile, reports of ios safari also acting similar)

New incognito tab
Go to site which does sso login against mulysa
Go to login
Use browser password autofill
Click login
=> csrf error

Cannot reproduce when not using browser autofill. Also lastpass pwd fill does work correctly.

Seems to work fine when going to login page without sso login request.

**Comment by sbeach92** [comment]
I think this problem has disappeared. Maybe along some chrome update?

**Comment by tswfi** [comment]
Now that you mention I haven't seen this either in a while.

Tried to replicate but wasn't able to quickly.

Lets close this.

**Comment by olmari** [comment]
I bet this had something related to do with https://github.com/TampereHacklab/mulysa/commit/5b70ee44d8be551358f8975efb3fd85a678e0b47 or such, which gave elaborate issues on email inking too in certain cases.
