### ISSUE TITLE
Implement SMS sending to control door activation

### ISSUE THREAD

**Issue by vranki** [TampereHacklab/mulysa#54]
SMS's should be sent to the door system according to the access rights status changes.

Some kind of SMS gateway is to be used. Simulated SMS sending also needed for development (add settings option).

Do the needful and test.

**Comment by tswfi** [comment]
dooractivator app contains base for this. it catches a signal and sends sms (twilio currently implemented and SMSBase can be used to implement more).

I have one twilio test account, but it is in trial mode and injects its own "sent with free twilio test account" or something like that in to the messages.
