### ISSUE TITLE
Finalize and test password reset feature

### ISSUE THREAD

**Issue by vranki** [TampereHacklab/mulysa#55]
There is already initial implementation of password reset.

Finalize it so that it's easy to use for users (links work etc).

Test that it actually sends e-mails in production environment and the links work.

**Comment by tswfi** [comment]
email sending should work now. configured smtp server for it

the default password reset view does not like running without admin

```
[2020-02-03 17:44:42,850] 611bd47d3b52482685b6cff4c46ef409 ERROR Internal Server Error: /accounts/password_reset/
Traceback (most recent call last):
  File "xxxx/urls/base.py", line 72, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'admin'
```

**Comment by vranki** [comment]
Tested working.
