### ISSUE TITLE
Build hardware and implement software to open door

### ISSUE THREAD

**Issue by vranki** [TampereHacklab/mulysa#57]
Build hardware that can open door using a relay. Door opening button already exists at lab (between textile and painting rooms) so cabling for it can be used.

Use any hardware such as Raspberry Pi or ESP. Your choice.

Requirements:
 - Must be able to get signal from server in cloud to open the door. Use for example mqtt, Matrix or other non-polling method. Signal must be authenticated / encrypted so that it can't be faked easily.
 - Hardware must survive power and network outages.
 - Software must be simple & robust - it can't fail or people will get angry.
 - Implement python class that acts as server for the door opener. This can be included in mulysa and/or other door opener services. Write a command line tool to demonstrate.

**Comment by tswfi** [comment]
or alternative. esp + rfid/ncf reader that can be put where it is needed.

esp reads the card and asks a mulysa public webinterface (https) "hi my espid is 123 and cardid is abc". Mulysa has knowledge that espid 123 == door or laser etc and card abc is the user and responds with either "has access" or "no access" and esp can then trigger gpio that can be used to activate door or laser or whatever.

**Comment by vranki** [comment]
This seems to be in progress.

**Comment by tswfi** [comment]
nfc reader and caller id hardware are about ready. next up the api endpoint for those. (Will start with the phone call endpoint as it will be simpler)

**Comment by tswfi** [comment]
Caller id is almost ready to go. Physical installation and a real phonenumber required.

**Comment by tswfi** [comment]
See also https://github.com/TampereHacklab/mulysa_callerid

**Comment by tswfi** [comment]
Closing this "epic". Lets open new issues as needed.
