### ISSUE TITLE
Logout for users goes to django admin page

### ISSUE THREAD

**Issue by vranki** [TampereHacklab/mulysa#89]
ATS reported that logout goes to admin page. Cos (as admin user) can't reproduce so this might be for non-admin users only?

**Comment by tswfi** [comment]
Also tested and cannot reproduce.

@akusav can you give steps to reproduce this

**Comment by akusav** [comment]
My bad could not reproduce logout to admin page, but password reset "Home"
links to django admin login page.

ke 19. helmik. 2020 klo 9.50 Tatu Wikman (notifications@github.com)
kirjoitti:
